# Generated by Django 5.0 on 2023-12-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalMgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
