# Generated by Django 5.0 on 2024-01-11 06:01

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalMgmt', '0002_remove_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='department',
            name='hospitals',
            field=models.ManyToManyField(related_name='departments', to='hospitalMgmt.hospital'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitalMgmt.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('Primary_Check', 'Primary_Check'), ('Consultation', 'Consultation'), ('Admitted', 'Admitted'), ('Under_treatment', 'Under_treatment'), ('Discharged', 'Discharged')], max_length=20)),
                ('remarks', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalMgmt.disease')),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitalMgmt.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalMgmt.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalMgmt.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientStatusUpdate',
        ),
    ]
