# Generated by Django 5.0 on 2024-01-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalMgmt', '0003_remove_patient_disease_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hospitals',
            field=models.ManyToManyField(related_name='department', to='hospitalMgmt.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
