# Generated by Django 5.0 on 2024-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalMgmt', '0004_alter_department_hospitals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
