# Generated by Django 5.0 on 2024-01-17 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalMgmt', '0005_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?91?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?91?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='update_type',
            field=models.CharField(choices=[('Primary_Check', 'Primary_Check'), ('Consultation', 'Consultation'), ('Admitted', 'Admitted'), ('Under_treatment', 'Under_treatment'), ('Discharged', 'Discharged')], max_length=15),
        ),
    ]
